general:
  vulnerabilities:
    # No fixes for these at this time
    - CVE-2022-2526
    - CVE-2022-40674
    # Disputed CVEs
    - CVE-2021-44716
    - CVE-2022-26280
    - CVE-2022-1271
    - CVE-2022-2175
