PODMON_CONTROLLER_LOG_LEVEL: "debug"
PODMON_CONTROLLER_LOG_FORMAT: "json"
PODMON_NODE_LOG_LEVEL: "debug"
PODMON_NODE_LOG_FORMAT: "json"
PODMON_ARRAY_CONNECTIVITY_POLL_RATE: 15
PODMON_ARRAY_CONNECTIVITY_CONNECTION_LOSS_THRESHOLD: 5
PODMON_SKIP_ARRAY_CONNECTION_VALIDATION: true
