name: Workflow
on:  # yamllint disable-line rule:truthy
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  sanitize:
    name: Check for forbidden words
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Run the forbidden words scan
        uses: dell/common-github-actions/code-sanitizer@main
        with:
          args: /github/workspace
  image_security_scan:
    name: Image Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go stable version
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: false
        id: go
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Checkout dell-csi-extensions
        uses: actions/checkout@v4
        with:
          repository: 'dell/dell-csi-extensions'
          path: dell-csi-extensions
      - name: Install Mockgen
        run: go get github.com/golang/mock/mockgen@v1.6.0
      - name: Get dependencies
        run: go mod download ; sudo apt update -y && sudo apt -y install dnf
      - name: Mod tidy
        run: go mod tidy
      - name: Build podmon Docker Image
        run: |
         podman build -t docker.io/podmon -f ./Dockerfile --build-arg GOIMAGE=golang:latest --build-arg BASEIMAGE="quay.io/dell/container-storage-modules/csm-base-image:nightly"
         podman save docker.io/library/podmon -o /tmp/podmon.tar
         docker load -i /tmp/podmon.tar
      - name: Trivy image scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: podmon
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          exit-code: '1'
          trivyignores: '.github/workflows/.trivyignore'
